[project]
name = "ml-portofolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "genericmaster", email = "rakhivhanithendo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ml-portofolio = "ml_portofolio:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
